/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3127bd5c-d4b6-42a5-a782-8253e6d74856",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_da1gvOdAy",
    "aws_user_pools_web_client_id": "136ga9dehrbk22aqgcc7dbgjb7",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://37gmky2jibfv5bln2biwhllsje.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-morjgtoi4ranfc6sgv6vbepoxi",
    "aws_user_files_s3_bucket": "smackeddobbieadmin-storage-d32qiutu9hfma3214854-budman",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
