/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b8556ee5-924b-4e4a-a26a-d86b698778d7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Nw6YSasrP",
    "aws_user_pools_web_client_id": "74kchqtic9suc40djq00fdcf5c",
    "oauth": {
        "domain": "smackeddobbieadmin232ea2c2-232ea2c2-budman.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://www.doobie.me/page-login/",
        "redirectSignOut": "https://www.doobie.me/page-logout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "FACEBOOK"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://yhte5c23ffepbj3vjnywaakxvu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-kws7rvdscffjlfggnud634us6y",
    "aws_user_files_s3_bucket": "smackeddobbieadmin-storage-d32qiutu9hfma3214854-budman",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
